server:
  port: 10010
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_stock
    username: root
    password: woshishen94SHEN
#    redis:
#      host: 172.16.116.100
mybatis-plus:
  # xml-location
  mapper-locations: classpath:src/main/resources/mapper/*.xml